spring:
  profiles:
    active:
      - dog
      - EN
      - prod

guru:
  username: superuser
  password: dbpassword
  jdbcurl: someUrlforDB

---
spring:
  profiles: prod
guru:
  username: ProdUserName
  password: ProdPassword
  jdbcurl: ProdURl
